# Generated by Django 3.0.5 on 2020-09-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheet',
            options={'verbose_name': 'Busqueda Asin', 'verbose_name_plural': 'Búsquedas Asin'},
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
